### ISSUE TITLE
Lstor failing to handle unicode filenames

### ISSUE THREAD

**Issue by byjtje** [pyroscope/pyrocore#104]
lstor fails to handle Unicode characters in filenames, for example "–" or any Asian character like "和","わ", etc.
Trying to run it, outputs an error
`WARNING  Bad metafile '\xe3\x82\x8f.torrent' (UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 0: ordinal not in range(128))`
failing on the first part of Unicode characters it encounters.
However not sure what the cause is, as https://github.com/pyroscope/pyrocore/blob/ff28b98ed1e69f2e13af9446a0954b941e6e75bb/src/pyrocore/util/metafile.py#L237 should successfully return a value after `text.decode("utf-8").encode("utf-8")`

**Comment by pyroscope** [comment]
Use `-v --debug` to find the actual source location (full traceback).

**Comment by byjtje** [comment]
```
➜  /tmp lstor -V -v --debug わ.torrent
DEBUG    Options: cron=False, debug=True, json=False, output=[], quiet=False, raw=False, reveal=False, skip_validation=True, verbose=True
INFO     Total time: 0.003 seconds.
Traceback (most recent call last):
  File "/home/xd/bin//lstor", line 11, in <module>
    load_entry_point('pyrocore', 'console_scripts', 'lstor')()
  File "/home/xd/.local/pyroscope/src/pyrocore/scripts/lstor.py", line 138, in run
    MetafileLister().run()
  File "/home/xd/.local/pyroscope/src/pyrocore/scripts/base.py", line 268, in run
    self.mainloop()
  File "/home/xd/.local/pyroscope/src/pyrocore/scripts/lstor.py", line 78, in mainloop
    quiet=(self.options.quiet and (self.options.output or self.options.raw)))
  File "/home/xd/.local/pyroscope/src/pyrocore/util/metafile.py", line 389, in checked_open
    log.warn("%s: %s" % (filename, exc))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 0: ordinal not in range(128)
```

Looking more into it, it looks like this is related to the torrent file. Files which don't need the `-V` flag work fine, but those which need it throw out errors:

The file I used for testing was https://archlinux.org/releng/releases/2020.12.01/torrent/ . With the normal name it works when using `lstor -V --raw archlinux-2020.12.01-x86_64.iso.torrent`, however renaming it to any of those characters throws out this error.

Same problem with files which work with just `lstor -V filename`, e.g. when lstor throws out `ValueError: Bad bencoded data - dict keys out of order?)` when not using the `-V` flag

**Comment by pyroscope** [comment]
git update and try again

**Comment by byjtje** [comment]
Fixed now, thank you very much
