### ISSUE TITLE
Fault:

### ISSUE THREAD

**Issue by ne0ark** [pyroscope/pyrocore#11]
I am getting this error with rtorrent 0.9.5:

python2.7/site-packages/pyrocore-0.4.2-py2.7.egg/pyrocore/util/xmlrpc.py", line 111, in __call__
return xmlrpclib.loads(xmlresp)[0][0]
File "/usr/lib/python2.7/xmlrpclib.py", line 1143, in loads
return u.close(), u.getmethodname()
File "/usr/lib/python2.7/xmlrpclib.py", line 799, in close
raise Fault(**self._stack[0])
Fault: <Fault -501: 'Could not find info-hash.'>

I am running python 2.7.10.

**Comment by pyroscope** [comment]
Use --debug to get useful diagnostics (esp. the xmlrpc method name called).

**Comment by pyroscope** [comment]
No feedback → closed.
