### ISSUE TITLE
unable to add torrent with resume support without adding folder name

### ISSUE THREAD

**Issue by Merlincool** [pyroscope/pyrocore#111]
Hi

Thanks this is great and it has help me a lot in torrent resuming larger torrents which would take hours to go through hash check most of the times. I am really thankful about this.

I am here to ask how can I do chtor and I want to ignore directory while hash check.

Say I have directory "test" and files are in it. I wish to skip folder and check only files within that test folder.

Also while adding torrent to rtorrent I want that my resume supported .torrent file (hash checked and created by above procedure) to ignore torrent path / main folder name of torrent and directly start seeding.

I read this section https://pyrocore.readthedocs.io/en/latest/references.html#cli-usage-chtor but I didn't understand syntax I should be using. Little weak to understand what is correct syntax.

Thanks.

**Comment by pyroscope** [comment]
It is quite unclear what you actually want, work with concrete examples.

**Comment by Merlincool** [comment]
> It is quite unclear what you actually want, work with concrete examples.

Okay I have a larger torrent, which does not have subdirectories within it, it just have files.

There are another newer smaller torrents (split from the pack). Let's say it has two files picked from that torrent.

So the smaller torrent (with two files) is created with folder. Say it has two files in folder called as "Small folder"

I want to cross seed this smaller torrent files with larger torrent pack. The problem is how do I skip hash check?

Because chtor would need something "Small folder" with files in it. How can I avoid "Small folder" hash check so that my chtor directly does hash check of files only from bigger torrent pack.

**Comment by pyroscope** [comment]
Just do a symlink or hardlink shadow of the file subset you want. Generally, multi-file torrents NEED a containing directory.

**Comment by Merlincool** [comment]
> Just do a symlink or hardlink shadow of the file subset you want. Generally, multi-file torrents NEED a containing directory.

Yes that's correct way but there are bunch of small torrents which I want to seed and not just one torrent. There are some 200-300 small torrents I would be cross seeding. Becomes too much of work. If it was some way to skip parent directory from smaller torrents and that could allow to cross seed torrent would have done some really magic.

**Comment by pyroscope** [comment]
Make each them single file, else no way.
