### ISSUE TITLE
mktor 

### ISSUE THREAD

**Issue by maxpayneovh** [pyroscope/pyrocore#120]
mktor adds 0bytes files to torrents can that be fixed?

**Comment by kannibalox** [comment]
Having 0-byte files is certainly a strange use case, but it appears to be [commonly allowed by other tools](https://github.com/transmission/transmission/issues/1453#issuecomment-1049424700), and there's nothing in the bittorrent spec that says they're invalid. You can use the `--exclude` flag to ignore specific files if needed.

**Comment by maxpayneovh** [comment]
and what 0byte would be using --exclude?

**Comment by kannibalox** [comment]
I simply meant you could use `--exclude <path to 0-byte file>` in order to exclude it. If you wanted to script that, you could do something fancier like
```bash
echo mktor <directory> <tracker> $(find <directory> -type f -empty -printf '--exclude "%P"')
```

**Comment by pyroscope** [comment]
Solved
