### ISSUE TITLE
Seeding torrents marked as 'finished' when they hit 1:1 despite rutorrent ratio group action to 'continue' 

### ISSUE THREAD

**Issue by Span24** [pyroscope/pyrocore#121]
Im running a pyrocore based rtorrent docker container on unraid server, In rutorrent I have ratio group actions set to continue seeding regardless of the ratio (I never want them to stop seeding). I have ratio group action configured to change the channel to 'delete ok' (unlimited) once the configured seed TIME is met (as you would expect, different per tracker). Nonetheless, once a seeded torrent tops a 1:1 ratio its marked as finished and seeding stops. The channel does change to 'delete ok' once the configured seed time is surpassed. However, if the ratio has not yet reached 1:1 then the torrent continues to seed. Its almost as if there is a (hidden) configuration or override somewhere forcing ANY torrent with a ratio of 1:1+ to 'finished' status regardless of the ratio group action settings.  I don't know much about pyrocore; is it possible that pyrocore is configured to change the status of a torrent after meeting 1:1+ ratio?  I contacted the docker container author at two different forums and have received no communication.
I have rtorrent installed in three separate locations (seedbox1, seedbox2, and local unraid docker) with the same plugins, etc.  All are configured the same and this (unraid docker) is the only install not working as configured and expected.  I'm uncertain if either seedbox uses pyrocore.

Thoughts?

**Comment by kannibalox** [comment]
Check if there is a process called `pyrotorque` running, or if the rtorrent.rc has any `rtcontrol` or `rtxmlrpc` commands in it. If not, pyrocore is just installed but has no bearing on ruTorrent/rTorrent.

**Comment by Span24** [comment]
> Check if there is a process called `pyrotorque` running, or if the rtorrent.rc has any `rtcontrol` or `rtxmlrpc` commands in it. If not, pyrocore is just installed but has no bearing on ruTorrent/rTorrent.

Thanks so very much for the reply and the assistance.  I checked and neither process is running nor is there any reference to the two commands in the rtorrent.rc file.  I have checked everything I know to check.  I have searched and searched.  I actually found a two year old post with the same question and two people indicating they shared the problem but not a single guess as to whats going on.  For me the greatest obstacle is not knowing which system is causing the issue.  It sounds as though I may be able to eliminate pyrocore tho.  

One question does come to my mind now, 'Is there a good reason for pyrocore to be installed into a docker distro but not used?'

Thanks again for your valuable time and assistance!

**Comment by kannibalox** [comment]
Yeah unfortunately sounds like it's an issue in ruTorrent in that case.

> One question does come to my mind now, 'Is there a good reason for pyrocore to be installed into a docker distro but not used?'

pyrocore is vastly superior for bulk operations, but is basically CLI only. Some people like to use ruTorrent for day-to-day stuff but pyrocore for e.g. mass changing directories or tags with ad-hoc `rtcontrol` commands via `docker exec`. Personally I have too many torrents for ruTorrent to be viable, but I see the appeal.

**Comment by Span24** [comment]
> Yeah unfortunately sounds like it's an issue in ruTorrent in that case.
> 
> > One question does come to my mind now, 'Is there a good reason for pyrocore to be installed into a docker distro but not used?'
> 
> pyrocore is vastly superior for bulk operations, but is basically CLI only. Some people like to use ruTorrent for day-to-day stuff but pyrocore for e.g. mass changing directories or tags with ad-hoc `rtcontrol` commands via `docker exec`. Personally I have too many torrents for ruTorrent to be viable, but I see the appeal.

Aaaah, I see.  It was included so that them who wish to use its advanced cli management functions can do so.  The rtcontrol and torque (cron) functions 'can' be scripted.

Thanks so very much!

**Comment by Span24** [comment]
I'm still really baffled by this problem.  I do not generally ever remove torrents but seed indefinitely so I'm left having to 'start' anything with a ratio better than 1:1 daily.

**Comment by Span24** [comment]
Well, I think that I've narrowed it down to a watchdog script that checks that (among other things) that openvpn is running and that the IP address has not changed.  On finding this it completely restarts rtorrent and re-initializes all plugins.  I think that somewhere in this process torrents with greater that 1:1 ratio are changed to 'finished' status.  I'll close this here and open an issue on the docker github repository for this distro.

Thanks!!!
