### ISSUE TITLE
error installing pyrocore

### ISSUE THREAD

**Issue by Ayanashi** [pyroscope/pyrocore#123]
Cloning into 'pyrobase'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.4]: errno=Connection timed out
[EDIT]
another error tryin' with pip  install --user pyrocore

> "pip install --user -U pyrocore
> Collecting pyrocore
>   Using cached pyrocore-0.5.3.zip (1.2 MB)
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [11 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/tmp/pip-install-seonu4z0/pyrocore_977cc52676684927bede419306432604/setup.py", line 10, in <module>
>           paver.tasks.main()
>         File "paver-minilib.zip/paver/tasks.py", line 878, in main
>         File "paver-minilib.zip/paver/tasks.py", line 846, in _launch_pavement
>         File "pavement.py", line 251
>           print "Upload @ http://pypi.python.org/pypi?:action=pkg_edit&name=%s" % ( options.setup.name,)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>       SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details."

**Comment by kannibalox** [comment]
This project does not currently support python 3. If running python 2 is not an option, you can try the python 3 pull request [here](https://github.com/pyroscope/pyrocore/pull/107), or I maintain a python 3 only fork [here](https://github.com/kannibalox/pyrosimple)
