### ISSUE TITLE
Torrent file generated by mktor incompatible with some trackers

### ISSUE THREAD

**Issue by 01100001** [pyroscope/pyrocore#17]
This what my `mktor` command looks like:

    mktor -pv --exclude 'somefile.nfo' -o 'my-directory.torrent' 'my-directory' http://example.com/passkey/announce

The tracker in question is AHD. After uploading that torrent file to AHD, the tracker checks the torrent file and makes some modifications to it. I am to seed using the torrent file that the tracker generates.

When I added the torrent file that AHD generated to rtorrent-ps (with pyrocore), this is the error I got:

    Could not create download: Download has unordered info dictionary.

This problem happens only with the torrent file created using `mktor` and then modified by AHD. Everything went fine when I created torrent using Transmission CLI's `transmission-create` command.

So, the way `mktor` creates the torrent file is somehow incompatible with some trackers. Would this be considered a bug?

**Comment by pyroscope** [comment]
It is considered a bug, of the tracker in question. When manipulation a metafile, they using simplistic code that breaks the structure of the metafile. You CAN try --no-cross-seed to circumvent their broken code, it might help.
