### ISSUE TITLE
Fix type of method d.last_active in rtorrent-0.8.6.rc for future compatibility

### ISSUE THREAD

**Issue by chros73** [pyroscope/pyrocore#18]
In this line `simple|value` should be just `simple` :
https://github.com/pyroscope/pyrocore/blob/master/src/pyrocore/data/config/rtorrent-0.8.6.rc#L43

More info here:
https://github.com/rakshasa/rtorrent/issues/384#issuecomment-194557639
https://github.com/rakshasa/rtorrent/commit/3edeb364bc7bfd3536e2b98dcc0f546aa2e249d2

**Comment by smasher816** [comment]
Thanks, this fixed my error after upgrading

```
rtorrent: Error in option file: ~/.rtorrent.rc:93: Error in option file: ~/.pyroscope/rtorrent-0.8.9.rc.default:49: Invalid type.
```

**Comment by pyroscope** [comment]
[master|391e36f] fix type of d.last_active
