### ISSUE TITLE
pyrotorque test ends in error

### ISSUE THREAD

**Issue by piperun** [pyroscope/pyrocore#20]
I noticed in my log file which logs execution of scripts, that pyrotorque seems to cause an error:

```

---
^@bash -c test ! -f ~/.pyroscope/run/pyrotorque || /home/rtorrentd/lib/pyroscope/bin/pyrotorque --cron

---
^@
--- Error ---
```

even though I have the pyrotorque file in said location:

`-rwxrwxrwx 1 rtduser rtduser 0 Apr 14 14:50 .pyroscope/run/pyrotorque`

**Comment by pyroscope** [comment]
Make sure your crontab has $HOME defined, and/or use "bash -x -c …"

**Comment by piperun** [comment]
It still gives out the same error after I set:
HOME=$(pwd)
in /etc/crontab

**Comment by pyroscope** [comment]
a crontab is not a script.

https://debian-handbook.info/

**Comment by piperun** [comment]
Sorry about that, even if I put it to:

HOME=/home/rtduser
as rtduser via the crontab -e command
or even edit the global /etc/crontab file with the same line, it does not work.

**Comment by piperun** [comment]
And as far as I've tried I can't find any information on how exactly the crontab should look like and if it is the global or the user crontab file I need to edit and I can't pinpoint exactly .

**Comment by chros73** [comment]
The env var should look like this: `HOME=/home/rtduser`

But it would be better in this way (I'm using something like this on Ubuntu 14.04):
* create a new file inside dir `/etc/cron.d` called `rtduser`
* include this line in it (modify the time, username, command): `*/5 * * * *     rtduser   bash -c test ! -f ~/.pyroscope/run/pyrotorque || /home/rtorrentd/lib/pyroscope/bin/pyrotorque --cron`

The trick is that we specify the user with which we run the command so we don't have to specify anything else.

**Comment by piperun** [comment]
Interesting, I will try it out later!

**Comment by pyroscope** [comment]
No new info, and this works if docs are followed.
