### ISSUE TITLE
Unable to use pyrocore from script

### ISSUE THREAD

**Issue by mafrosis** [pyroscope/pyrocore#22]
Following the instructions from the [docs](http://pyrocore.readthedocs.io/en/latest/scripts.html#interactive-use-in-a-python-shell) - I should be able to use `pyrocore` as a library.

    > python
    Python 2.7.11+ (default, Apr 17 2016, 14:00:29)
    [GCC 5.3.1 20160413] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from pyrocore import connect
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: cannot import name connect

I attempted to use the code from the first example on the same page but that creates some unintelligible results. Perhaps I'm using it wrong?

    > python
    Python 2.7.11+ (default, Apr 17 2016, 14:00:29)
    [GCC 5.3.1 20160413] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from pyrocore import config
    >>> proxy = config.engine.open()
    >>> print list(config.engine.items())
    [('open', <function <lambda> at 0x7f1d78b94848>)]
    >>> config.engine.items()
    [('open', <function <lambda> at 0x7f1d78b94848>)]
    >>> config.engine.items()[0][1]()
    >>> 

The script on the page uses the hashbang `#! /usr/bin/env python-pyrocore` - but `python-pyrocore` doesn't exist in my path.

`rtcontrol` is working fine on the command line!

**Comment by pyroscope** [comment]
* Make sure you use git HEAD.
* ~/bin/python-pyrocore is just a symlink into the virtualenv that the installer script creates, ensuring the right interpreter is used.

**Comment by mafrosis** [comment]
Working great from HEAD. Apologies for not realising that pypi was so out of date!
