### ISSUE TITLE
PyPi out of date

### ISSUE THREAD

**Issue by ne0ark** [pyroscope/pyrocore#3]
It appears https://pypi.python.org/pypi/pyrocore is out of date.

Are you planning on updating to the latest version?

RE: https://github.com/pyroscope/pyrobase/issues/2

**Comment by pyroscope** [comment]
When the whole moving situation is done, there will be a release – the last actually that will support pre-syntax-change rtorrent, which will then allow to shed a lot of overhead.

**Comment by kannibalox** [comment]
awesome!
