### ISSUE TITLE
rtmv complains "WARNING No download item found for "foo", skipping!"

### ISSUE THREAD

**Issue by DavidGriffith** [pyroscope/pyrocore#31]
Sometimes when I try to use rtmv to fix a poorly-named directory, I get this complaint: `WARNING No download item found for "foo", skipping!`.  What, exactly, is the problem that rtmv is complaining about and how do I fix it?

**Comment by chros73** [comment]
There's an IRC (https://github.com/pyroscope/pyrocore) channel with lot of guys on it, you can also ask this there.

**Comment by pyroscope** [comment]
Provide a path to move that is actually registered in the client. And use -v or --debug.

**Comment by pyroscope** [comment]
Closing since this will be rewritten eventually, anyway.
