### ISSUE TITLE
TreeWatch - new torrents not added

### ISSUE THREAD

**Issue by xsmile** [pyroscope/pyrocore#37]
libtorrent version: c167c5a9e0bcf0df23ae5efd91396aae0e37eb87 (2016-12-12)
rTorrent version: 10ce6864b81aaf2a7e43e9959940696b47aac2bc (2016-11-04)
rtorrent-ps: 5f836fefcde5ac0a60d4c953715e11ad35a30ed3 (2017-02-12)
pyrocore: 4eb75a3604def4c001d08fab418c5ef1a9ecfdc2 (2017-02-10)

I have set up a treewatch that recognizes new torrents. However it fails with following message and rTorrent does not them:
```<Fault -506: "Method 'load_verbose' not defined"> [pyrocore.torrent.watch.TreeWatch]```

`load_verbose` was replaced with `load.verbose` according to the new rTorrent syntax and might be the cause of the issue.

**Comment by chros73** [comment]
Probably, just modify it in the source code until it will be changed.

**Comment by xsmile** [comment]
@chros73: I tried it already:
`Unknown hash for load.verbose([...].torrent) @ scgi://127.0.0.1:5000 [pyrocore.torrent.watch.TreeWatch]`

**Comment by pyroscope** [comment]
The workaround, as already mentioned on IRC, is to start rt 096 with -M -K.

**Comment by Blackclaws** [comment]
@pyroscope I tried that. Even though rtorrent itself mentions deprecated commands are enabled the error stays the same

**Comment by pyroscope** [comment]
Well, then the solution is to run a released stable version of rT, not git. treewatch runs fine with rT 096 here, but I guess I should start to run my test instances without the old commands enabled.
