### ISSUE TITLE
Socket path as variable in rtorrent config

### ISSUE THREAD

**Issue by xsmile** [pyroscope/pyrocore#39]
Pyrotorque does not establish a connection if the configuration file for rTorrent uses a variable for the socket path. See following example.

rtorrent.rc
```
method.insert = cfg.sock_file,      private|const|string, "/run/rtorrent/rtorrent.sock"
...
network.scgi.open_local = (cfg.sock_file)
```

torque.log
```
2017-03-03 20:45:00 WARNING  Can't connect to 'scgi:///(cfg.sock_file)' ([Errno 2] No such file or directory) [pyrocore.torrent.jobs.EngineStats]
```

**Comment by pyroscope** [comment]
https://github.com/pyroscope/pimp-my-box/blob/390753eef1f7ba817ee6499083f37206175b89ff/roles/rtorrent-ps/templates/rtorrent/rtorrent.rc#L84

This is just not possible.
