### ISSUE TITLE
broken initial install process

### ISSUE THREAD

**Issue by joshoram80** [pyroscope/pyrocore#4]
Issues installing Pyroscope on new VPS

Spoke to pyrocore on IRC. Chatlog below

<Stuntard> new server having installation errors.
<Stuntard> https://pastee.org/eyjy4
<Stuntard> trying to force Python 2.7.9 with pyenv but isntall script still uses 2.6.5
<Stuntard> working with provider to get it working. Build worked but https://pastee.org/g9wu8 when using rtcontrol --version
<@pyroscope> call ". bootstrap.sh" in the pyrobase dir
<@pyroscope> also # Pass "/usr/bin/python2", or whatever else fits, to the script,
<@pyroscope> # if "/usr/bin/python" is not a suitable version (e.g. Python 3)
<@pyroscope> stuff should also still work with 2.6  for now
<Stuntard> https://pastee.org/pwqh9
<Stuntard> then https://pastee.org/ezsu6 again

Python Diagnostics
------------------------
1.4.5
{'enc_def': 'ascii',
 'enc_fs': 'UTF-8',
 'lang': 'en_US.UTF-8',
 'maxuchr': 65535,
 'os_uc_names': False,
 'prefix': '/home/owner/.pyenv/versions/venv2.7.9',
 'sh': '/bin/bash',
 'term': 'xterm',
 'tz': ('EST', 'EDT'),
 'version': '2.7.9 (default, May  5 2015, 06:39:50) \n[GCC 4.4.3]'}

OS Diagnostics
---------------------
Linux SpicyWiener 2.6.38-16-server #67~lucid1-Ubuntu SMP Fri Sep 7 18:36:10 UTC          2012 x86_64 GNU/Linux
Ubuntu Ubuntu 10.04.4 LTS 10.04 lucid
      2 model name      : Intel(R) Xeon(R) CPU           X5570  @ 2.93GHz
             total       used       free     shared    buffers     cached
Mem:          3963       3871         92          0         71       2939
 07:10:46 up  6:59,  2 users,  load average: 0.05, 0.07, 0.15
Rakshasa's BitTorrent client version 0.9.2.
        libcurl.so.4 => /usr/lib/libcurl.so.4 (0x00007f85e5b2d000)
        libtorrent.so.14 => /usr/local/lib/libtorrent.so.14 (0x00007f85e582b000)
        libxmlrpc.so.3 => /usr/local/lib/libxmlrpc.so.3 (0x00007f85e540c000)
        libssl.so.0.9.8 => /lib/libssl.so.0.9.8 (0x00007f85e323c000)
        libcrypto.so.0.9.8 => /lib/libcrypto.so.0.9.8 (0x00007f85e2eaa000)
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND

**Comment by RSully** [comment]
I'm getting same error (#5) with python 2.7.6. I'll close my issue.

**Comment by RSully** [comment]
If I revert to a521a2b61f8e2e14633842f91c58bca65555b4df (the commit I used on my previous VM's install) and comment out the `git pull` in `update-to-head.sh` it works. Looks like something has broken in this repo recently.

**Comment by joshoram80** [comment]
which git pull? There is 2 of them

**Comment by RSully** [comment]
@joshoram80 the one that breaks things if you don't? line 35
