### ISSUE TITLE
torque: allow stopping if too many downloads are running

### ISSUE THREAD

**Issue by jmdevince** [pyroscope/pyrocore#45]
Currently PyroTorque only starts items it won't stop items. Some downloading methods automatically add the torrent started. (see Remote Torrent Adder for Chrome). You can add torrents paused but pyrotorque won't start those because is_open=no is part of the startable filter by default.

**Comment by pyroscope** [comment]
State transitions in both directions would add a lot of complexity and instability. No.

If I understand this, #46 will solve your problem, I'll look into that. If not, ask the "adder" project to support *all* client states, including stopped. This isn't an exotic feature…
