### ISSUE TITLE
'Invalid key' error after adding rtcontrol filter commands in config.

### ISSUE THREAD

**Issue by 01100001** [pyroscope/pyrocore#48]
Adding this snippet ([straight from the docs](http://pyrocore.readthedocs.io/en/latest/usage.html#integrating-rtcontrol-into-the-curses-ui)) to views.rc:

```
# UI/VIEW: Use rtcontrol filter (^X s=KEYWORD, ^X t=TRACKER, ^X f="FILTER")
method.insert = s,simple|private,"execute.nothrow=rtcontrol,--detach,-qV,\"$cat=*,$argument.0=,*\""
method.insert = t,simple|private,"execute.nothrow=rtcontrol,--detach,-qV,\"$cat=\\\"alias=\\\",$argument.0=\""
method.insert = f,simple|private,"execute.nothrow=rtcontrol,--detach,-qV,$argument.0="
```

Results in this error when launching `rtorrent`:

```
rtorrent: Failed to parse command line option: Error in option file: ~/torrents/rtorrent.rc:39: Error in option file: ~/torrents/rtorrent.d/.import.rc:16: Error in option file: ~/a/torrents/rtorrent.d/views.rc:34: Invalid key.
```

I have also tried this old snippet:

```
# UI/CMD: Use rtcontrol filter (^X s=KEYWORD, ^X t=TRACKER, ^X f="FILTER")
method.insert = s,simple|private,"execute.nothrow=\"$cat=$pyro.bin_dir=,rtcontrol\",--detach,-qV,\"$cat=*,$argument.0=,*\""
method.insert = t,simple|private,"execute.nothrow=\"$cat=$pyro.bin_dir=,rtcontrol\",--detach,-qV,\"$cat=\\\"alias=\\\",$argument.0=\""
method.insert = f,simple|private,"execute.nothrow=\"$cat=$pyro.bin_dir=,rtcontrol\",--detach,-qV,$argument.0="
```

Nothing works. Any idea why?

**Comment by chros73** [comment]
Only `method.insert` can be the problem.
Which rtorrent version do you use?

**Comment by 01100001** [comment]
*0.9.6-PS-1.1-dev* considering that's the only directory in `~/.local/rtorrent`. Within the rTorrent interface (at the top center), it shows *rTorrent PS-1.0-58-g55b0ee9 0.9.6/0.13.6*.

**Comment by chros73** [comment]
Sorry, the `Invalid key` message means that either `s`, `t`, `f` is/are already declared (with `method.insert = s,`...) somewhere in your configs. Check which lines is `34` in views.rc then search for that key in your configs.

**Comment by 01100001** [comment]
@chros73 I searched both `rtorrent.rc` and inside `/rtorrent.d/`. I searched for `s,`, `t,` and `f,` and found nothing relevant (the error persists with any of the 3 lines).

**Comment by pyroscope** [comment]
Note box directly above the docs location you linked… "You already have the following configuration commands, if you followed the Configuration Guide."

You already included them!

**Comment by 01100001** [comment]
Ah, now I think I know why.

I am running multiple instances of rTorrent, and am passing the option `-D rtorrent_rc=PATH_TO/rtorrent.rc` to `rtcontrol` as [stated here in the docs](http://pyrocore.readthedocs.io/en/latest/howto.html#switching-to-the-rtorrent-rc-of-an-instance). And the `rtorrent_rc` setting in `config.ini` is actually commented out, so the commands weren't working in the curses UI.

[Didn't see this](http://pyrocore.readthedocs.io/en/latest/howto.html#customizing-the-default-configuration-per-instance) earlier; now I know what to do. Thanks! 😎
