### ISSUE TITLE
Anyway to find unloaded torrents?

### ISSUE THREAD

**Issue by 01100001** [pyroscope/pyrocore#50]
When I add `*.torrent` files in bulk to rTorrent's watch directory (e.g. 250 at once), it sometimes skips loading 1 or 2 torrent files. These torrent files reside in the watch directory but aren't loaded/started and are therefore not shown in the ncurses interface. This happens too often (at least 1-in-3) for me to ignore.

Is there anyway to quickly identify such `*.torrent` files so that I can quickly remove and add them to the watch directory again?

**Comment by chros73** [comment]
> When I add *.torrent files in bulk to rTorrent's watch directory (e.g. 250 at once), it sometimes skips loading 1 or 2 torrent files. 

Strange, and after when you add these manually are they loaded fine?

> Is there anyway to quickly identify such *.torrent files ...

You can use something similar to pyroscope's brilliant [orphans](https://github.com/pyroscope/pyrocore/blob/master/src/pyrocore/data/config/templates/orphans.txt) idea.

**Comment by 01100001** [comment]
> Strange, and after when you add these manually are they loaded fine?

Yep! Weird, right?

> You can use something similar to pyroscope's brilliant orphans idea.

Doesn't seem to be working. I tried this:

```
rtcontrol -qO ~/orphans.txt --define=dir=/home/loki/torrents/watch alias=mytracker
```

And it returned a bunch of filenames that are all loaded just fine (and seeding) in rTorrent. 🤔

**Comment by pyroscope** [comment]
Please use the mailing list or IRC for such questions, the issue tracker is no support platform. And hash collisions are ONE cause metafile are not loaded.
