### ISSUE TITLE
mktor doesn't work if there are unicode characters in the filename

### ISSUE THREAD

**Issue by llwu** [pyroscope/pyrocore#51]
To reproduce: Create a directory with a Japanese name, and put a file with a Japanese name under it. Then try to create a .torrent of this directory using `mktor`.

**Comment by pyroscope** [comment]
attach a zip with a small demo file tree, else this is not reproducible. make sure everything is utf8 ecnoded.

**Comment by llwu** [comment]
[All That Jazz - ジブリ・ジャズ2 [V0].zip](https://github.com/pyroscope/pyrocore/files/1032509/All.That.Jazz.-.2.V0.zip)


`llwu@UNDERHELP:/mnt/media$ mktor  -X JPopSuki -p -o unicode.torrent "All That Jazz - ジブリ・ジャズ2 [V0]"/ "https://localhost:420"
INFO     Creating 'unicode.torrent' for data in 'All That Jazz - \xe3\x82\xb8\xe3\x83\x96\xe3\x83\xaa\xe3\x83\xbb\xe3\x82\xb8\xe3\x83\xa3\xe3\x82\xba2 [V0]'...
INFO     Total time: 0.197 seconds.
Traceback (most recent call last):
  File "/home/llwu/bin/mktor", line 11, in <module>
    load_entry_point('pyrocore', 'console_scripts', 'mktor')()
  File "/home/llwu/.local/pyroscope/src/pyrocore/scripts/mktor.py", line 180, in run
    MetafileCreator().run()
  File "/home/llwu/.local/pyroscope/src/pyrocore/scripts/base.py", line 240, in run
    self.mainloop()
  File "/home/llwu/.local/pyroscope/src/pyrocore/scripts/mktor.py", line 156, in mainloop
    comment=self.options.comment, created_by="PyroScope %s" % self.version, callback=callback
  File "/home/llwu/.local/pyroscope/src/pyrocore/util/metafile.py", line 639, in create
    meta, totalhashed = self._make_meta(tracker_url, root_name, private, progress)
  File "/home/llwu/.local/pyroscope/src/pyrocore/util/metafile.py", line 570, in _make_meta
    info, totalhashed = self._make_info(piece_size, progress, self.walk() if self._fifo else sorted(self.walk()))
  File "/home/llwu/.local/pyroscope/src/pyrocore/util/metafile.py", line 491, in _make_info
    "path": filepath.replace(os.sep, '/').split('/'),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 4: ordinal not in range(128)`

I tried putting a pdb breakpoint in there. But actually the filepath.replace(... works fine from the pdb prompt. Just throws an exception in the code.

**Comment by pyroscope** [comment]
Works without a hitch here. Make sure you run the newest code, and also…

http://pyrocore.readthedocs.io/en/latest/troubleshooting.html#providing-diagnostic-information
