### ISSUE TITLE
Put full path in the pyroscope files instead of relying on tilde expansion

### ISSUE THREAD

**Issue by mwoodson** [pyroscope/pyrocore#54]
I am looking for advice, or even suggest an issue.

I just installed pyrocore according to the docs.  Then I went to add the section to my .rtorrent.rc file.

When I kick off rtorrent manually, from the prompt, it works fine.

However when I try to kick it off from a screen session within screen, it doesn't work.  I have tracked the issue down to the ~(tilde) that are referenced.  From within screen, rtorrent doesn't like the tildes.

I see two options:

1) figure out how to start rtorrent in screen that will use tildes.  A note in the rtorrent directory says that it doesn't like tildes in the .rtorrent.rc conf file.

https://github.com/rakshasa/rtorrent/blob/ce0008510723b6c96c86f8fe944affc84f90cd69/doc/scripts/init/rtorrentInitScreen.bash#L6-L7

I was hoping I just needed an env var to make this work.  I haven't found it if that's the case.

2) have pyrocore put in the full path rather than ~.  This needs to be done in not only:

.rtorrent.rc

but also the files in the .pyroscope dir that the .rtorrent.rc file includes.

Thoughts?

**Comment by pyroscope** [comment]
Set HOME if you start stuff from starved environments (cron, init, systemd). Or use "bash -l -c …".

So in conclusion, the fix goes into that buggy init script.
