### ISSUE TITLE
rtxmlrpc Fault -503

### ISSUE THREAD

**Issue by GiowGiow** [pyroscope/pyrocore#68]
I was trying to stop all commands using pyrocore, i read the Docs but I didn't get it fully because there were not that much examples i could grasp my head on, so I tried running this command:

rtxmlrpc d.multicall2 "" d.stop=

After that i tried running with the debug arg so I could ask here. What am I missing ?

```
~$ rtxmlrpc --debug d.multicall2 "" d.stop=
DEBUG    Options: as_import=False, config_dir=None, config_file=[], cron=False, debug=True, defines=[], quiet=False, repr=False, session=False, verbose=True, xml=False
DEBUG    Loading '/home/giow/.pyroscope/config.ini'...
DEBUG    Loading '/home/giow/.pyroscope/config.py'...
DEBUG    Loading rtorrent config from '/home/giow/.rtorrent.rc'
DEBUG    rtorrent.rc: scgi_port = localhost:53511
DEBUG    CMD MAPPINGS ARE: {'log=': 'print=', 'log': 'print'}
DEBUG    XMLRPC raw request: "<?xml version='1.0'?>\n<methodCall>\n<methodName>system.client_version</methodName>\n<params>\n</params>\n</methodCall>\n"
DEBUG    system.client_version() took 10.597 secs
DEBUG    XMLRPC raw request: "<?xml version='1.0'?>\n<methodCall>\n<methodName>system.library_version</methodName>\n<params>\n</params>\n</methodCall>\n"
DEBUG    system.library_version() took 0.008 secs
DEBUG    MAPPING for (0, 8, 7) added: {'d.get_down_total': 'd.down.total', 'd.get_up_total': 'd.up.total', 'd.get_up_rate': 'd.up.rate', 'd.save_session': 'd.save_full_session', 'd.get_down_rate': 'd.down.rate', 'd.get_custom': 'd.custom', 'get_name': 'session.name', 'view_filter': 'view.filter', 'session_save': 'session.save', 't.get_url': 't.url', 'view_list': 'view.list', 'get_session': 'session.path', 'system.get_cwd': 'system.cwd', 'd.set_custom': 'd.custom.set', 'd.multicall': 'd.multicall2', 'get_directory': 'directory.default'}
DEBUG    CMD MAPPINGS ARE: {'view_list=': 'view.list=', 'd.get_down_total': 'd.down.total', 'd.get_up_total': 'd.up.total', 'get_name=': 'session.name=', 't.get_url=': 't.url=', 'log=': 'print=', 'session_save=': 'session.save=', 'd.get_up_rate': 'd.up.rate', 'd.save_session': 'd.save_full_session', 'd.get_down_rate': 'd.down.rate', 'd.get_custom': 'd.custom', 'd.multicall': 'd.multicall2', 'view_filter': 'view.filter', 'session_save': 'session.save', 't.get_url': 't.url', 'd.get_down_total=': 'd.down.total=', 'view_list': 'view.list', 'get_session': 'session.path', 'd.get_up_rate=': 'd.up.rate=', 'view_filter=': 'view.filter=', 'system.get_cwd': 'system.cwd', 'd.set_custom=': 'd.custom.set=', 'd.get_custom=': 'd.custom=', 'log': 'print', 'get_session=': 'session.path=', 'd.get_down_rate=': 'd.down.rate=', 'd.set_custom': 'd.custom.set', 'get_name': 'session.name', 'get_directory=': 'directory.default=', 'get_directory': 'directory.default', 'd.save_session=': 'd.save_full_session=', 'd.multicall=': 'd.multicall2=', 'system.get_cwd=': 'system.cwd=', 'd.get_up_total=': 'd.up.total='}
DEBUG    XMLRPC raw request: "<?xml version='1.0'?>\n<methodCall>\n<methodName>d.multicall2</methodName>\n<params>\n<param>\n<value><string></string></value>\n</param>\n<param>\n<value><string>d.stop=</string></value>\n</param>\n</params>\n</methodCall>\n"
INFO: Bad data packets written to '/tmp/xmlrpc2scgi-1000.xml'
DEBUG    d.multicall2('', 'd.stop=') took 0.001 secs
ERROR    While calling d.multicall2('', 'd.stop='): <Fault -503: 'Could not find view.'>
DEBUG    XMLRPC stats: 3 req, out 444 bytes [213 bytes max], in 605 bytes [300 bytes max], 3534.752ms/3535.332ms avg latency
DEBUG    Total time: 10.637 seconds.

```

**Comment by kannibalox** [comment]
The 2nd argument to d.multicall2 should be the view See https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#term-d-multicall2

**Comment by GiowGiow** [comment]
When It is omitted it should pass the default view, that is what I tried to do

**Comment by pyroscope** [comment]
But you passed a view, named `d.stop=`.

**Comment by GiowGiow** [comment]
Now i get it, I'm stupid and thought d.stop= was the argument, not the view.
Then I run:
_rtxmlrpc --debug d.multicall2 d.stop=_
and I get:

`
DEBUG    Options: as_import=False, config_dir=None, config_file=[], cron=False, debug=True, defines=[], quiet=False, repr=False, session=False, verbose=True, xml=False
DEBUG    Loading '/home/giow/.pyroscope/config.ini'...
DEBUG    Loading '/home/giow/.pyroscope/config.py'...
DEBUG    Loading rtorrent config from '/home/giow/.rtorrent.rc'
DEBUG    rtorrent.rc: scgi_port = localhost:53511
DEBUG    CMD MAPPINGS ARE: {'log=': 'print=', 'log': 'print'}
DEBUG    XMLRPC raw request: "<?xml version='1.0'?>\n<methodCall>\n<methodName>system.client_version</methodName>\n<params>\n</params>\n</methodCall>\n"
DEBUG    system.client_version() took 0.001 secs
DEBUG    XMLRPC raw request: "<?xml version='1.0'?>\n<methodCall>\n<methodName>system.library_version</methodName>\n<params>\n</params>\n</methodCall>\n"
DEBUG    system.library_version() took 0.001 secs
DEBUG    MAPPING for (0, 8, 7) added: {'d.get_down_total': 'd.down.total', 'd.get_up_total': 'd.up.total', 'd.get_up_rate': 'd.up.rate', 'd.save_session': 'd.save_full_session', 'd.get_down_rate': 'd.down.rate', 'd.get_custom': 'd.custom', 'get_name': 'session.name', 'view_filter': 'view.filter', 'session_save': 'session.save', 't.get_url': 't.url', 'view_list': 'view.list', 'get_session': 'session.path', 'system.get_cwd': 'system.cwd', 'd.set_custom': 'd.custom.set', 'd.multicall': 'd.multicall2', 'get_directory': 'directory.default'}
DEBUG    CMD MAPPINGS ARE: {'view_list=': 'view.list=', 'd.get_down_total': 'd.down.total', 'd.get_up_total': 'd.up.total', 'get_name=': 'session.name=', 't.get_url=': 't.url=', 'log=': 'print=', 'session_save=': 'session.save=', 'd.get_up_rate': 'd.up.rate', 'd.save_session': 'd.save_full_session', 'd.get_down_rate': 'd.down.rate', 'd.get_custom': 'd.custom', 'd.multicall': 'd.multicall2', 'view_filter': 'view.filter', 'session_save': 'session.save', 't.get_url': 't.url', 'd.get_down_total=': 'd.down.total=', 'view_list': 'view.list', 'get_session': 'session.path', 'd.get_up_rate=': 'd.up.rate=', 'view_filter=': 'view.filter=', 'system.get_cwd': 'system.cwd', 'd.set_custom=': 'd.custom.set=', 'd.get_custom=': 'd.custom=', 'log': 'print', 'get_session=': 'session.path=', 'd.get_down_rate=': 'd.down.rate=', 'd.set_custom': 'd.custom.set', 'get_name': 'session.name', 'get_directory=': 'directory.default=', 'get_directory': 'directory.default', 'd.save_session=': 'd.save_full_session=', 'd.multicall=': 'd.multicall2=', 'system.get_cwd=': 'system.cwd=', 'd.get_up_total=': 'd.up.total='}
DEBUG    XMLRPC raw request: "<?xml version='1.0'?>\n<methodCall>\n<methodName>d.multicall2</methodName>\n<params>\n<param>\n<value><string>d.stop=</string></value>\n</param>\n</params>\n</methodCall>\n"
INFO: Bad data packets written to '/tmp/xmlrpc2scgi-1000.xml'
DEBUG    d.multicall2('d.stop=') took 0.001 secs
ERROR    While calling d.multicall2('d.stop='): <Fault -501: 'Unsupported target type found.'>
DEBUG    XMLRPC stats: 3 req, out 394 bytes [163 bytes max], in 615 bytes [310 bytes max], 0.361ms/0.692ms avg latency
DEBUG    Total time: 0.035 seconds.
`

**Comment by kannibalox** [comment]
Take a look at the examples in the doc I linked, the syntax is `rtxmlrpc '' $view $command= [$command=...]`. `$view` can be an empty string, but that's not the same as not having it.

**Comment by GiowGiow** [comment]
Got it now, it is working, thanks!
