### ISSUE TITLE
Question: method for cross-seeding downloaded torrents with matching info hash?  mktor/chtor can't work?

### ISSUE THREAD

**Issue by TheBloke** [pyroscope/pyrocore#76]
Hello

I am trying to cross-seed torrents downloaded from several private trackers.  This works if the tracker modifies the metafile in some way, but when the metafiles are 100% identical I get the message "Info hash already used by another torrent" and can't seed the second or subsequent torrents.  

I saw in the pyrocore docs that ```mktor``` can be used to create metafiles with a unique hash for cross-seeding, allowing one data directory to serve many trackers.  The docs talk about doing this when uploading a torrent, but I hoped it could also be used to modify existing torrents I've downloaded.  I also saw that ```chtor``` can be used to add the same ```x_cross_seed``` field.

However when I have tried these tools I've found that both result in my modified torrent getting a new HASH allocated, resulting in "Unregistered torrent" replies from the trackers I use. 

Reading further, I think I now understand that the HASH is generated from the entire info section of the metafile - meaning that adding ```x_cross_seed``` must always generate a new HASH?  **EDIT:** Actually, I guess that's the whole point of x_cross_seed - to generate a different HASH.  At first I thought x_cross_seed had some special meaning to rtorrent, enabling it to load the same HASH twice if they differed on x_cross_seed.  But I guess it just ensures there's no HASH clash in the first place?

Therefore it's imposible to modify a downloaded metafile to allow cross seeding in rtorrent?  

I'd be grateful if anyone could confirm if that's the case, and let me know if there's any other suitable methods for cross-seeding torrents downloaded from multiple (private) trackers.  One option is to run multiple instances of rtorrent, one per tracker, but I'd prefer to avoid that if possible.

Thanks very much in advance.

TB.

PS. I'm posting this in pyrocore because I started out hoping to use mktor/chtor.  But if that's impossible it might better belong in rtorrent-PS.  Let me know if I should close this and post there instead.

**Comment by pyroscope** [comment]
It belongs in neither issue tracker, but in the mailing list or reddit.
