### ISSUE TITLE
mktor --fast-resume without announce url?

### ISSUE THREAD

**Issue by phxn** [pyroscope/pyrocore#78]
Hello,

I am trying to use mktor to create a fast resume torrent, the problem I'm having is that the tracker in question does not require you to enter a tracker url upon creating torrents.

I've checked a regular .torrent from the site with lstor and the URL is listed as:

https://tracker.site.net/announce.php?passkey=********************************

As you can see, the passkey is asterisked out.

Is it possible to create mktor --fast-resume with this limitation or am I out of luck?

**Comment by pyroscope** [comment]
The issue tracker is no support channel. And there is `--reveal`.
