### ISSUE TITLE
How to integrate this into a docker rtorrent environment

### ISSUE THREAD

**Issue by RaymondSchnyder** [pyroscope/pyrocore#81]
Hello,

I want to add this to my rtorrent/rutorrent container image.
Now im trying around a bit and what is mostly stopping me is the "update-to-head.sh" script, as its always trying to write to  /home/rtorrent instead of the directory i provide with the PYRO_CONFIG_DIR ENV variable. Even when i specify it explicitly, it gets ignored.

This is a bit annoying, is there an already made approach?

Do you have any idea what i could do? My current approach is more a workaround than something else...

**Comment by pyroscope** [comment]
The script writes where you place it. If you do things like docker, you're supoposed to be able to read bash. besides the full dockerfile in the rt-ps repo,

**Comment by RaymondSchnyder** [comment]
Hmm. Weird.
Maybe i need glasses, but those Commands... idk:
![grafik](https://user-images.githubusercontent.com/12892508/51134983-46b54c80-1839-11e9-9380-2ffba2727569.png)
![grafik](https://user-images.githubusercontent.com/12892508/51134999-4cab2d80-1839-11e9-9203-d14c899d2095.png)
They seem pretty static to me. Weird. :/

Esspecially this part tho
![grafik](https://user-images.githubusercontent.com/12892508/51135028-5e8cd080-1839-11e9-946c-2361b7a4eedf.png)
Do you see the userhome there? I do not lol

**Comment by kannibalox** [comment]
Here's a stupidly simple Dockerfile that I use:
```
FROM python:3

RUN mkdir /app

WORKDIR /app

COPY pyroscope .

RUN pip install -r requirements.txt
```
The `requirements.txt` in question:
```
https://github.com/kannibalox/pyrobase/archive/py3.tar.gz
https://github.com/kannibalox/pyrocore/archive/py3.tar.gz
requests
APScheduler>=2.0.2,<3
Tempita>=0.5.1

```

**Comment by pyroscope** [comment]
`${foo:-default}` is a syntax found in `man bash`. In a Dockerfile, you need to explicitly set HOME because there is no bashrc etc that sets it. You need to understand those tools to be successful.
