### ISSUE TITLE
lstor fails with BencodeError: Trailing data at offset XXXX

### ISSUE THREAD

**Issue by n-other** [pyroscope/pyrocore#9]
Hello,

for the last few months I am getting problems with parsing torrent files coming from one specific tracker. other tools seem to create and validate those torrent file, however lstor fails to parse them.
here is the example link to the one of such torrents: http://new-rutor.org/parse/d.rutor.org/download/239533

can u plz check?

**Comment by pyroscope** [comment]
lstor has a --help option like all the tools, which *does* list the -V option…

Also, please use the mailing list for support, not the issue tracker.

**Comment by n-other** [comment]
well, I tried it before writing here. -V does not change error output. the error is still there.
