### ISSUE TITLE
Adding date to session

### ISSUE THREAD

**Issue by phxn** [pyroscope/pyrocore#91]
Hello, I am trying to add the torrent added date to my rtorrent session and it used to work fine (in past installs), but this is no longer working in my current install.

I am adding this to my .rtorrent.rc:

`method.set_key = event.download.inserted_new,loaded_time,"d.custom.set=addtime,$cat=$system.time=;d.save_full_session="`

When I try to delete torrents by date using rtcontrol filters I get no results.

**Comment by pyroscope** [comment]
Use the provided includes, not some modified and buggy copy.

**Comment by phxn** [comment]
I don't understand what you mean by that. I've read all your docs and I can't find anything related to adding date to session.

This is what I've used in the past and it worked.

Oh well...

**Comment by pyroscope** [comment]
Having that line or not has no impact whatsoever on pyrocore. Include the standard config as per docs, and backfill your existing data as per docs.

**Comment by phxn** [comment]
I thought rtcontrol was part of pyrocore? My bad.

I don't understand why this worked for me in the past and now it doesn't.

I guess the problem lies in the fact that I want a "light" install, and I want to use my configs with only the requirements I need to use rtcontrol. I don't want everything.

It's not a big deal now anyway, I went back to Deluge. rtorrent speeds were terrible.
