### ISSUE TITLE
pyrotorque no module named requests

### ISSUE THREAD

**Issue by forsomefun2** [pyroscope/pyrocore#93]
Not sure what is going on here I had to call
/home/rtorrent/.local/pyroscope/bin/python2 /usr/local/bin/pip install requests
Not sure if my paths are messed up or what happened but this was the only way I could fix this problem

Spent hours working on it
of course rtorrent is my pyrotorque user

**Comment by forsomefun2** [comment]
I had to do the same to get treewatch to work
pyinotify was the module missing

**Comment by pyroscope** [comment]
the docs state what extra deps to install, and how. read them.
